# Import Library

In [1]:
from google_play_scraper import app, reviews
import pandas as pd

# Scraping All Review From Game App "Roblox"

In [2]:
scrapreview, _ = reviews(
    'com.roblox.client',
    lang='id',
    country='id',
    count=10000
)

In [3]:
import csv

with open('ulasan_game_roblox.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Review'])
    for review in scrapreview:
        writer.writerow([review['content']])

# Load Dataset

In [4]:
game_reviews_df = pd.DataFrame(scrapreview)
game_reviews_df.shape
game_reviews_df.head()
game_reviews_df.to_csv('ulasan_game_roblox.csv', index=False)

In [5]:
game_reviews_df = pd.DataFrame(scrapreview)
print(f"Shape of game_reviews_df after re-creation: {game_reviews_df.shape}")

Shape of game_reviews_df after re-creation: (10000, 11)

In [6]:
game_reviews_df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,ff479260-2a43-4550-9862-3a0d16879170,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,jelek ngelag,1,0,None,2026-05-09 19:03:41,None,None,None
1,11eef1d9-bcd9-479c-ad83-69b493b3cf55,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,woi Roblox tolong bantuin akun gw kembalikan s...,5,0,2.720.1167,2026-05-09 19:02:00,None,None,2.720.1167
2,deb90458-cc3b-4cd2-aeca-2b517f62fd6c,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,ini gimana akun saya tidak bisa di masuki udah...,1,1,2.717.985,2026-05-09 19:01:53,None,None,2.717.985
3,5ab68163-0c9c-4d77-a04e-486df6c22aef,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,bagus banget,5,0,2.719.1340,2026-05-09 19:01:06,None,None,2.719.1340
4,a7695c25-7ec2-401e-9a75-46598d6df695,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,apaan sih gua cuma putar lagu langsung di gak ...,2,0,2.719.1340,2026-05-09 19:00:35,None,None,2.719.1340
...,...,...,...,...,...,...,...,...,...,...,...
9995,a127c1c4-281c-4b41-bfde-02ce120cdb16,Asvi Maulidya,https://play-lh.googleusercontent.com/a-/ALV-U...,"game nya seru sih,tapi tolong dong jangan veri...",3,0,None,2026-04-30 14:38:34,None,None,None
9996,24b84cc6-70f2-48dd-b464-13d22cf02e0b,KPRTANPARIBET,https://play-lh.googleusercontent.com/a/ACg8oc...,seru banget mainnya,5,0,2.717.985,2026-04-30 14:38:15,None,None,2.717.985
9997,62a78373-fea8-45c0-b655-542c5f13dc8f,Alfarizki Rendra,https://play-lh.googleusercontent.com/a/ACg8oc...,game ini seru banyak map nya tapi sayang udah ...,4,0,None,2026-04-30 14:34:25,None,None,None
9998,fde16f07-7c77-4731-875b-27567f46f0a7,Fitri Handayani,https://play-lh.googleusercontent.com/a/ACg8oc...,kembalikan roblox yang dulu!!! 😭,1,0,None,2026-04-30 14:33:21,None,None,None
9999,3312be92-cefb-430e-bdde-979076649fde,Yeni Nuraeni,https://play-lh.googleusercontent.com/a/ACg8oc...,bagus tapi saya ingin menambahkan vitur hapus ...,5,0,2.716.875,2026-04-30 14:32:58,None,None,2.716.875

In [7]:
game_reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              10000 non-null  object
 1   userName              10000 non-null  object
 2   userImage             10000 non-null  object
 3   content               9998 non-null   object
 4   score                 10000 non-null  int64
 5   thumbsUpCount         10000 non-null  int64
 6   reviewCreatedVersion  7275 non-null   object
 7   at                    10000 non-null  datetime64[ns]
 8   replyContent          0 non-null      object
 9   repliedAt             0 non-null      object
 10  appVersion            7275 non-null   object
dtypes: datetime64[ns](1), int64(2), object(8)
memory usage: 859.5+ KB

In [8]:
# Check null value
game_reviews_df.isnull().sum()

reviewId                    0
userName                    0
userImage                   0
content                     2
score                       0
thumbsUpCount               0
reviewCreatedVersion     2725
at                          0
replyContent            10000
repliedAt               10000
appVersion               2725
dtype: int64

In [9]:
# Drop columns where all values are NaN
clean = game_reviews_df.dropna(axis=1, how='all')

print(f"Shape of 'clean' DataFrame after targeted cleaning: {clean.shape}")
display(clean.head())

Shape of 'clean' DataFrame after targeted cleaning: (10000, 9)

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,appVersion
0,ff479260-2a43-4550-9862-3a0d16879170,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,jelek ngelag,1,0,None,2026-05-09 19:03:41,None
1,11eef1d9-bcd9-479c-ad83-69b493b3cf55,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,woi Roblox tolong bantuin akun gw kembalikan s...,5,0,2.720.1167,2026-05-09 19:02:00,2.720.1167
2,deb90458-cc3b-4cd2-aeca-2b517f62fd6c,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,ini gimana akun saya tidak bisa di masuki udah...,1,1,2.717.985,2026-05-09 19:01:53,2.717.985
3,5ab68163-0c9c-4d77-a04e-486df6c22aef,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,bagus banget,5,0,2.719.1340,2026-05-09 19:01:06,2.719.1340
4,a7695c25-7ec2-401e-9a75-46598d6df695,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,apaan sih gua cuma putar lagu langsung di gak ...,2,0,2.719.1340,2026-05-09 19:00:35,2.719.1340

In [10]:
clean.isnull().sum()

reviewId                   0
userName                   0
userImage                  0
content                    2
score                      0
thumbsUpCount              0
reviewCreatedVersion    2725
at                         0
appVersion              2725
dtype: int64

In [11]:
clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              10000 non-null  object
 1   userName              10000 non-null  object
 2   userImage             10000 non-null  object
 3   content               9998 non-null   object
 4   score                 10000 non-null  int64
 5   thumbsUpCount         10000 non-null  int64
 6   reviewCreatedVersion  7275 non-null   object
 7   at                    10000 non-null  datetime64[ns]
 8   appVersion            7275 non-null   object
dtypes: datetime64[ns](1), int64(2), object(6)
memory usage: 703.3+ KB

In [12]:
clean = clean.drop(columns=['reviewCreatedVersion', 'appVersion'])
print(f"Shape of 'clean' DataFrame after dropping columns: {clean.shape}")
display(clean.head())

Shape of 'clean' DataFrame after dropping columns: (10000, 7)

,reviewId,userName,userImage,content,score,thumbsUpCount,at
0,ff479260-2a43-4550-9862-3a0d16879170,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,jelek ngelag,1,0,2026-05-09 19:03:41
1,11eef1d9-bcd9-479c-ad83-69b493b3cf55,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,woi Roblox tolong bantuin akun gw kembalikan s...,5,0,2026-05-09 19:02:00
2,deb90458-cc3b-4cd2-aeca-2b517f62fd6c,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,ini gimana akun saya tidak bisa di masuki udah...,1,1,2026-05-09 19:01:53
3,5ab68163-0c9c-4d77-a04e-486df6c22aef,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,bagus banget,5,0,2026-05-09 19:01:06
4,a7695c25-7ec2-401e-9a75-46598d6df695,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,apaan sih gua cuma putar lagu langsung di gak ...,2,0,2026-05-09 19:00:35

In [13]:
clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   reviewId       10000 non-null  object
 1   userName       10000 non-null  object
 2   userImage      10000 non-null  object
 3   content        9998 non-null   object
 4   score          10000 non-null  int64
 5   thumbsUpCount  10000 non-null  int64
 6   at             10000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(4)
memory usage: 547.0+ KB

In [14]:
clean.isnull().sum()

reviewId         0
userName         0
userImage        0
content          2
score            0
thumbsUpCount    0
at               0
dtype: int64

In [15]:
clean['content'] = clean['content'].fillna('')

In [16]:
clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   reviewId       10000 non-null  object
 1   userName       10000 non-null  object
 2   userImage      10000 non-null  object
 3   content        10000 non-null  object
 4   score          10000 non-null  int64
 5   thumbsUpCount  10000 non-null  int64
 6   at             10000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(4)
memory usage: 547.0+ KB

In [17]:
# Save cleaned file to csv
clean.to_csv('ulasan_game_roblox_cleaned.csv')